# Generated by Django 5.2.1 on 2025-05-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0002_remove_borrowing_created_at_borrowing_borrow_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowing",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
